In [27]:
#import helper function
%run helper_functions.py
%run NeuralNetwork.py

In [12]:
import tensorflow as tf
from matplotlib import pyplot
import numpy as np 
import math 
import time 

# Import Data

In [3]:
#get data 
fashion_mnist = tf.keras.datasets.fashion_mnist
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()    

#normalize features 
X_train, X_test = normalizeX(X_train, X_test)    
#OHE target 
y_train, y_test = oheY(y_train, y_test)
    
print("X train: ", X_train.shape, "Y train: ",  y_train.shape,  "X test: ", X_test.shape,  "Y_test: ", y_test.shape)


X train:  (60000, 784) Y train:  (60000, 10) X test:  (10000, 784) Y_test:  (10000, 10)


sample parameters for NN: <br>
num_features = 784,  num_classes = 10,  num_neurons = [512, 256, 256, 128, 128, 64],
 activation_fxn = ['ReLU', 'ReLU', 'ReLU', 'ReLU', 'ReLU', 'ReLU'],  learning_rate = 0.001, epochs = 2, batch_size = 128

## 2-layer network

## ReLU

In [8]:
num_features = 784 
num_classes = 10
num_neurons = [500, 300]
activation_fxn = ['ReLU', 'ReLU']
learning_rate = 0.1
epochs = 10
batch_size = 200


myNN = NeuralNetwork(num_features, num_classes, num_neurons, activation_fxn, learning_rate, epochs, batch_size  )
myNN.train(X_train, y_train)
t_accuracy = myNN.predict(X_test, y_test)
print("Test accuracy: ", t_accuracy, "%")


##############################################
Number of features: 784 
Number of classes: 10 
Number of layers: 3 
Learning rate 0.1
Layer 1 Number of Neurons: 500, Activation Function: ReLU
Weight: (500, 784), Bias: (500, 1)
Layer 2 Number of Neurons: 300, Activation Function: ReLU
Weight: (300, 500), Bias: (300, 1)
Layer 3 Number of Neurons: 10, Activation Function: softmax
Weight: (10, 300), Bias: (10, 1)
##############################################
num of batches:  300
epoch:  0
epoch  0 batch  0 loss:  0.23038557806555032 accuracy:  10.5
epoch  0 batch  100 loss:  0.2335244958890184 accuracy:  14.0
epoch  0 batch  200 loss:  0.23066766719431833 accuracy:  18.0
epoch:  1
epoch  1 batch  0 loss:  0.2303345643909273 accuracy:  12.0
epoch  1 batch  100 loss:  0.23020572310925227 accuracy:  13.0
epoch  1 batch  200 loss:  0.2305769781284751 accuracy:  14.0
epoch:  2
epoch  2 batch  0 loss:  0.23032299574299483 accuracy:  12.0
epoch  2 batch  100 loss:  0.22990715536559855 accuracy: 

## Sigmoid

In [29]:
num_features = 784 
num_classes = 10
num_neurons = [500, 300]
activation_fxn = ['sigmoid', 'sigmoid']
learning_rate = 0.1
epochs = 10
batch_size = 200


myNN = NeuralNetwork(num_features, num_classes, num_neurons, activation_fxn, learning_rate, epochs, batch_size  )
myNN.train(X_train, y_train)
t_accuracy = myNN.predict(X_test, y_test)
print("Test accuracy: ", t_accuracy, "%")


##############################################
Number of features: 784 
Number of classes: 10 
Number of layers: 3 
Learning rate 0.1
Layer 1 Number of Neurons: 500, Activation Function: sigmoid
Weight: (500, 784), Bias: (500, 1)
Layer 2 Number of Neurons: 300, Activation Function: sigmoid
Weight: (300, 500), Bias: (300, 1)
Layer 3 Number of Neurons: 10, Activation Function: softmax
Weight: (10, 300), Bias: (10, 1)
##############################################
num of batches:  300
epoch  0 batch  0 loss:  0.27773431475426624 accuracy:  10.5
epoch  0 batch  100 loss:  0.2355061446983658 accuracy:  15.0
epoch  0 batch  200 loss:  0.23384706366759805 accuracy:  13.5
epoch  1 batch  0 loss:  0.23191493639222113 accuracy:  13.0
epoch  1 batch  100 loss:  0.23225108963160362 accuracy:  17.0
epoch  1 batch  200 loss:  0.23242190505471508 accuracy:  10.5
epoch  2 batch  0 loss:  0.23153531571757005 accuracy:  13.0
epoch  2 batch  100 loss:  0.23133423543609938 accuracy:  17.0
epoch  2 batch  

In [30]:
t_accuracy = myNN.predictwithOutput(X_test, y_test)

total:  10000
[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
[9 2 1 1 6 1 4 6 5 7 4 5 7 3 4 1 2 4 8 0 2 5 7 9 1 4 6 0 9 3]
correct: 975


## Increase Number of layers

In [18]:
num_features = 784
num_classes = 10
num_neurons = [512, 256, 128, 64, 32]
activation_fxn = ['ReLU', 'ReLU', 'ReLU', 'ReLU', 'ReLU']
learning_rate = 0.001
epochs = 10
batch_size = 128

myNN = NeuralNetwork(num_features, num_classes, num_neurons, activation_fxn, learning_rate, epochs, batch_size  )
myNN.train(X_train, y_train)
t_accuracy = myNN.predict(X_test, y_test)
print("Test accuracy: ", t_accuracy, "%")


##############################################
Number of features: 784 
Number of classes: 10 
Number of layers: 6 
Learning rate 0.001
Layer 1 Number of Neurons: 512, Activation Function: ReLU
Weight: (512, 784), Bias: (512, 1)
Layer 2 Number of Neurons: 256, Activation Function: ReLU
Weight: (256, 512), Bias: (256, 1)
Layer 3 Number of Neurons: 128, Activation Function: ReLU
Weight: (128, 256), Bias: (128, 1)
Layer 4 Number of Neurons: 64, Activation Function: ReLU
Weight: (64, 128), Bias: (64, 1)
Layer 5 Number of Neurons: 32, Activation Function: ReLU
Weight: (32, 64), Bias: (32, 1)
Layer 6 Number of Neurons: 10, Activation Function: softmax
Weight: (10, 32), Bias: (10, 1)
##############################################
num of batches:  469
epoch:  0
epoch  0 batch  0 loss:  0.2302523749482639 accuracy:  7.81
epoch  0 batch  100 loss:  0.23097788359367527 accuracy:  7.81
epoch  0 batch  200 loss:  0.23414196853127095 accuracy:  8.59
epoch  0 batch  300 loss:  0.23202303492431314 acc

In [19]:
num_features = 784
num_classes = 10
num_neurons = [1024, 512, 256, 128, 64]
activation_fxn = ['ReLU', 'ReLU', 'ReLU', 'ReLU', 'ReLU']
learning_rate = 0.001
epochs = 10
batch_size = 128

myNN = NeuralNetwork(num_features, num_classes, num_neurons, activation_fxn, learning_rate, epochs, batch_size  )
myNN.train(X_train, y_train)
t_accuracy = myNN.predict(X_test, y_test)
print("Test accuracy: ", t_accuracy, "%")


##############################################
Number of features: 784 
Number of classes: 10 
Number of layers: 6 
Learning rate 0.001
Layer 1 Number of Neurons: 1024, Activation Function: ReLU
Weight: (1024, 784), Bias: (1024, 1)
Layer 2 Number of Neurons: 512, Activation Function: ReLU
Weight: (512, 1024), Bias: (512, 1)
Layer 3 Number of Neurons: 256, Activation Function: ReLU
Weight: (256, 512), Bias: (256, 1)
Layer 4 Number of Neurons: 128, Activation Function: ReLU
Weight: (128, 256), Bias: (128, 1)
Layer 5 Number of Neurons: 64, Activation Function: ReLU
Weight: (64, 128), Bias: (64, 1)
Layer 6 Number of Neurons: 10, Activation Function: softmax
Weight: (10, 64), Bias: (10, 1)
##############################################
num of batches:  469
epoch:  0
epoch  0 batch  0 loss:  0.23018873982634674 accuracy:  9.38
epoch  0 batch  100 loss:  0.235272978084049 accuracy:  7.03
epoch  0 batch  200 loss:  0.24263616699297338 accuracy:  16.41
epoch  0 batch  300 loss:  0.2419484251537

In [24]:
num_features = 784
num_classes = 10
num_neurons = [100, 50, 25]
activation_fxn = ['ReLU', 'sigmoid', 'ReLU']
learning_rate = 0.01
epochs = 5
batch_size = 200

myNN = NeuralNetwork(num_features, num_classes, num_neurons, activation_fxn, learning_rate, epochs, batch_size  )
myNN.train(X_train, y_train)
t_accuracy = myNN.predict(X_test, y_test)
print("Test accuracy: ", t_accuracy, "%")

##############################################
Number of features: 784 
Number of classes: 10 
Number of layers: 4 
Learning rate 0.01
Layer 1 Number of Neurons: 100, Activation Function: ReLU
Weight: (100, 784), Bias: (100, 1)
Layer 2 Number of Neurons: 50, Activation Function: sigmoid
Weight: (50, 100), Bias: (50, 1)
Layer 3 Number of Neurons: 25, Activation Function: ReLU
Weight: (25, 50), Bias: (25, 1)
Layer 4 Number of Neurons: 10, Activation Function: softmax
Weight: (10, 25), Bias: (10, 1)
##############################################
num of batches:  300
epoch  0 batch  0 loss:  0.23032785304492318 accuracy:  8.0
epoch  0 batch  100 loss:  0.23028085062867093 accuracy:  11.0
epoch  0 batch  200 loss:  0.2302400771357526 accuracy:  9.5
epoch  1 batch  0 loss:  0.2302708608664011 accuracy:  9.0
epoch  1 batch  100 loss:  0.23023282378070736 accuracy:  10.0
epoch  1 batch  200 loss:  0.23039010962417106 accuracy:  7.0
epoch  2 batch  0 loss:  0.23022308203043015 accuracy:  9.5
ep

In [28]:
t_accuracy = myNN.predictwithOutput(X_test, y_test)


total:  10000
[9 9 9 9 9 9 9 9 9 9]
[9 2 1 1 6 1 4 6 5 7]
correct: 991
